title: "Data Analyst Notebook"
description: "El meu repositori personal de trucs, codi i anàlisis d'utilitat diària."
baseurl: "" 
url: ""

# Configuració de Google Analytics
google_analytics: "G-XXXXXXXXXX"

permalink: /:title/
markdown: kramdown
theme: null
