title: "Quadern personal d'anàlisi"
description: "Notes tècniques sobre estadística, modelització i anàlisi de dades."
lang: ca
url: "https://alberthr.github.io" # URL final del site
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

permalink: /entrades/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
