# Configuración básica de Jekyll
title: Mi Sitio Jekyll
description: Un sitio generado con Jekyll en GitHub Pages
theme: minima  # Puedes usar otros temas si quieres
collections:
  articulos:
    output: true
